### ISSUE TITLE
How do you export to global scope?

### ISSUE THREAD

**Issue by mpranjic** [sbalbalosa/meteor-6to5#1]
For me, `export var foo = 'bar';` does not work because it compiles into `var foo = exports.foo = 'bar';` and `exports` is not defined.
Using `foo = 'bar';` or `this.foo = 'bar';` is not defined because it compiles into `'use strict;'` which does not allow it.

Am I missing something? It seems that no one has issues with this except me :)

**Comment by ghost** [comment]
You can create a file globals.js where you create all your global variables. This file should not be in strict mode. Also make sure that it is loaded before the other files.

Using the ES6 module system with exports and imports would make the globals unnecessary. But currently I don't know an easy way to use it. So you may just stick with globals for now.

EDIT:
You can also just have one global for your app `MyApp = {}` (would be the globals.js file). Then you can create new keys on that one in strict mode. For example `MyApp.MyModule = { /* Module Code */ }`.

**Comment by mpranjic** [comment]
Thanks :)
